name = "DBConnector"
uuid = "5242bac9-aa14-4800-b46b-fcd14df13057"
authors = ["Jacob Zelko <jacobszelko@gmail.com>", "Fareeda Abdelazeez"]
version = "0.1.0"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
DBInterface = "2.5"
LibPQ = "1.15"
MySQL = "1.4"
SQLite = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
